AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-poc-harry

Globals:
  Function:
    Timeout: 20

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: CodeDeploy_sam-artifacts

Outputs:
  DeploymentBucketArn:
    Description: "DeploymentBucket ARN"
    Value: !GetAtt DeploymentBucket.Arn
    Export:
      Name:
        !GetAtt DeploymentBucket.Arn