AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-poc-harry

Globals:
  Function:
    Timeout: 20

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sam-poc-deployment-artifacts

Outputs:
  DeploymentBucket:
    Description: "DeploymentBucket ARN"
    Value: !GetAtt DeploymentBucket.Arn